postgres:
  username: "placeholder"
  password: "placeholder"
  databaseNames:
    barcabot: "placeholder"
    hangfire: "placeholder"
apis:
  footballData:
    token: "placeholder"
  apiFootball:
    token: "placeholder"
    season: "placeholder"
plotly:
  username: "placeholder"
  token: "placeholder"
discordToken: "placeholder"