***REMOVED***
  username: "placeholder"
  password: "placeholder"
***REMOVED***
    footballData: "placeholder"
    hangfire: "placeholder"
    players: "placeholder"
***REMOVED***
  footballData: "placeholder"
  apiFootball: "placeholder"
***REMOVED***
  username: "placeholder"
  token: "placeholder"
discordToken: "placeholder"
