postgres:
  username: "placeholder"
  password: "placeholder"
  databaseNames:
    barcabot: "placeholder"
    hangfire: "placeholder"
apiTokens:
  footballData: "placeholder"
  apiFootball: "placeholder"
plotly:
  username: "placeholder"
  token: "placeholder"
discordToken: "placeholder"

